/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACircle: typeof import('./components/A/Circle.vue')['default']
    AFigure: typeof import('./components/A/Figure.vue')['default']
    PartGift: typeof import('./components/Part/Gift.vue')['default']
    PartRespond: typeof import('./components/Part/Respond.vue')['default']
    PartWelcome: typeof import('./components/Part/Welcome.vue')['default']
    PartWhat: typeof import('./components/Part/What.vue')['default']
    PartWhen: typeof import('./components/Part/When.vue')['default']
    PartWhere: typeof import('./components/Part/Where.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAge: typeof import('./components/The/Age.vue')['default']
    TheClock: typeof import('./components/The/Clock.vue')['default']
    TheCountdown: typeof import('./components/The/Countdown.vue')['default']
    TheHeader: typeof import('./components/The/Header.vue')['default']
    TheHero: typeof import('./components/The/Hero.vue')['default']
    TheMap: typeof import('./components/The/Map.vue')['default']
    TheSlide: typeof import('./components/The/Slide.vue')['default']
    TheToc: typeof import('./components/The/Toc.vue')['default']
  }
}
