/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCountdown: typeof import('./components/The/Countdown.vue')['default']
    TheFigure: typeof import('./components/The/Figure.vue')['default']
    TheHeader: typeof import('./components/The/Header.vue')['default']
    TheHero: typeof import('./components/The/Hero.vue')['default']
    TheSlide: typeof import('./components/The/Slide.vue')['default']
    TheToc: typeof import('./components/The/Toc.vue')['default']
  }
}
