/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./components/index.vue')['default']
    Countdown: typeof import('./components/The/Countdown.vue')['default']
    Header: typeof import('./components/The/Header.vue')['default']
    Input: typeof import('./components/The/Input.vue')['default']
    Readme: typeof import('./components/readme.md')['default']
    Ring: typeof import('./components/The/Ring.vue')['default']
    RingBuilder: typeof import('./components/Ring/Builder/Builder.vue')['default']
    RingBuilderFieldset: typeof import('./components/Ring/Builder/Fieldset.vue')['default']
    RingBuilderFormset: typeof import('./components/Ring/Builder/Formset.vue')['default']
    RingCircle: typeof import('./components/Ring/Circle.vue')['default']
    RingOne: typeof import('./components/Ring/One.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./components/The/Slide.vue')['default']
    TheBuilder: typeof import('./components/The/Builder.vue')['default']
    TheCountdown: typeof import('./components/The/Countdown.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/The/Header.vue')['default']
    TheInput: typeof import('./components/The/Input.vue')['default']
    TheRing: typeof import('./components/The/Ring/Ring.vue')['default']
    TheRingBkp: typeof import('./components/TheRingBkp.vue')['default']
    TheRingBuilder: typeof import('./components/The/Ring/Builder.vue')['default']
    TheRingCircle: typeof import('./components/The/Ring/Circle.vue')['default']
    TheRingOne: typeof import('./components/The/Ring/One.vue')['default']
    TheSlide: typeof import('./components/The/Slide.vue')['default']
  }
}
